version: '3.4'

services:
  webapicoffee:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "44379:80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  my-app:
    ports:
      - '3000:3000'
    stdin_open: true
    volumes:
      - ../my-app:/app
      - /app/node_modules
 
